config/routes.rb
ReceiveEverything::Application.routes.draw do
  resources :comments do
    member do
      get :reply
    end
  end

  resources :share_links do
    member do
      get :sharer
      put :shared
    end
  end

  resources :goddesses
  resources :purchases do
    collection do
      get :mine
    end
  end

  devise_for :creatrixes
  resources :prices

  resources :inclusions do
    member do
      put :move_higher
      put :move_lower
    end
  end
  
  resources :accesses

  resources :products do
    resources :inclusions
    member do
      get :display
      put :move_higher
      put :move_lower
    end
    collection do
      get :browse
    end
  end

  resources :meditations do
    collection do
      get :browse
    end
    member do
      get :display
    end
  end

  devise_for :mystics
  resources :mystics do
    collection do
      get :logged_in
      post :grant
    end
  end
  get 'facebook_new_session' => 'facebook#new_session', :as => 'new_session_facebook'
  
  root :to => 'products#browse'

end

app/models/access.rb
class Access < ActiveRecord::Base
  belongs_to :meditation
  belongs_to :mystic
  validates :mystic_id, :presence => true
  validates :meditation_id, :uniqueness => {scope: :mystic_id}, :presence => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :mystic
  belongs_to :subject, :polymorphic => true
  has_many :replies, :foreign_key => :is_reply_to, :class_name => 'Comment'
  belongs_to :is_reply_to_comment, :foreign_key => :is_reply_to, :class_name => 'Comment'
  
  validate :text, :presence => true
  
  scope :on_subject, lambda { |subject| where(:subject_id => subject.id, :subject_type => subject.class.name)}
  scope :active, lambda { where('hidden is null or hidden = ?', false) }
  scope :not_reply, lambda { where(:is_reply_to => nil) }
end

app/models/creatrix.rb
class Creatrix < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  def active_for_authentication?
    super && active?
  end
end

app/models/goddess.rb
class Goddess < ActiveRecord::Base
  belongs_to :mystic
end

app/models/inclusion.rb
class Inclusion < ActiveRecord::Base
  belongs_to :product
  belongs_to :meditation
  validates :product_id, :presence => true
  validates :meditation_id, :uniqueness => {scope: :product_id}, :presence => true
  acts_as_list :scope => :product_id
end

app/models/meditation.rb
class Meditation < ActiveRecord::Base
  has_many :inclusions
  has_many :products, :through => :inclusions
  
  has_many :accesses
  has_many :mystics, :through => :accesses
  
  has_many :comments, :as => :subject
  
  scope :not_in_product, lambda { |product| product.inclusions.any? ? where('id not in (?)', product.inclusions.map(&:meditation_id)) : nil }
  scope :free, lambda { where :free => true }
  scope :active, lambda { where :active => true }
  
  def current_price_in_cents
    products.first.andand.current_price_in_cents
  end
  
  def current_price_in_dollars
    current_price_in_cents.andand./ 100.0
  end
end

app/models/mystic.rb
class Mystic < ActiveRecord::Base
  has_many :accesses
  has_many :meditations, :through => :accesses
  has_many :purchases
  attr_accessor :skip_welcome_email

  after_create :gain_access_to_free_meditations, :send_email_to_aweber, :deliver_gift_email

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  def name
    if first_name?
      first_name
    else
      email[/[^@]+/]
    end
  end
  
  def has_access_to? meditation
    meditations.include? meditation
  end
  
  def has_access_to_product? product
    purchases.map(&:product).include?(product) or product.meditations.all? { |meditation| has_access_to? meditation }
  end
  
  def password_required?
    super unless facebook_id.present?
  end
  
  def gain_access_to_free_meditations
    Meditation.free.each do |meditation|
      accesses.create :meditation => meditation
    end
  end
  
  def send_email_to_aweber
    return if @skip_welcome_email
    begin
      oauth = AWeber::OAuth.new ENV['AWEBER_CONSUMER_KEY'], ENV['AWEBER_CONSUMER_SECRET']
      oauth.authorize_with_access ENV['AWEBER_ACCESS_TOKEN'], ENV['AWEBER_ACCESS_TOKEN_SECRET']
      aweber = AWeber::Base.new oauth
      receive_everything_mailing_list = aweber.account.lists.find_by_name ENV['AWEBER_MAILING_LIST_NAME']
      receive_everything_mailing_list.subscribers.create 'email' => email
    rescue StandardError, AWeber::OAuthError, AWeber::NotFoundError, AWeber::UnknownRequestError, AWeber::RateLimitError, AWeber::ForbiddenRequestError, AWeber::CreationError => error
      Rails.logger.error error.inspect
    end
  end
  
  def deliver_gift_email
    return if @skip_welcome_email
    Gift.initiate(self).deliver
  end
end

app/models/price.rb
class Price < ActiveRecord::Base
  belongs_to :product
  
  scope :current, lambda { where('(start_time < ? or start_time is null) and (end_time > ? or end_time is null)', Time.now, Time.now) }
  scope :active, lambda { where :active => true }
  scope :lowest, lambda { order :cents }
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :inclusions, :order => :position
  has_many :meditations, :through => :inclusions
  has_many :prices
  
  scope :ordered, lambda { order(:position) }
  scope :active, lambda { where(:active => true) }
  acts_as_list
  
  def current_price
    prices.current.active.lowest.first
  end
  
  def current_price_in_cents
    current_price.andand.cents.to_i
  end
  
  def current_price_in_dollars
    current_price_in_cents / 100.0
  end
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :product
  belongs_to :mystic
  belongs_to :price
end

app/models/share_link.rb
class ShareLink < ActiveRecord::Base
  belongs_to :creatrix
end

app/helpers/accesses_helper.rb
module AccessesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def display_comments_on subject
    div_for subject, 'display_comments_on' do
      Comment.on_subject(subject).active.not_reply.map do |comment|
        display_comment(comment)
      end.join.html_safe
    end
  end
  
  def display_comment comment, class_name = nil
    div_for(comment, :class => class_name) do
      "#{comment.mystic.name}: #{comment.text} #{link_to('Reply', reply_comment_path(comment), :remote => true)}".html_safe
    end + 
    comment.replies.active.map do |reply|
      display_comment reply, "reply#{class_name}"
    end.join.html_safe
  end
  
  def comment_form_for subject, reply_to = nil
    form_for subject.comments.new, :remote => true, :class => 'comment_form' do |f|
      f.text_area(:text) +
      f.submit("Save") +
      f.hidden_field(:subject_type, :value => subject.class.name) +
      f.hidden_field(:subject_id, :value => subject.id) + 
      (reply_to ? f.hidden_field(:is_reply_to, :value => reply_to.id) : '')
    end
  end
end

app/helpers/facebook_helper.rb
module FacebookHelper
end

app/helpers/goddesses_helper.rb
module GoddessesHelper
end

app/helpers/inclusions_helper.rb
module InclusionsHelper
end

app/helpers/mystics_helper.rb
module MysticsHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/gift/initiate.html.erb
<p>
  Hello!
</p>

<p>
  We are learning about receiving gifts.  Here is one I have for you.  It is a meditation, an audio file, and I would like for you to listen to it!
</p>

<p>
  You should be able to open this file on any computer and load it onto any phone, device or player.  If you would like to share it with someone else, you can, but I ask that instead of sending them your file, please direct them to <%= link_to 'receiveeverything.com', root_url %> and tell them that they can get the meditation, and more, by just providing their email address (or signing up via Facebook).  Thank you!!  The choice is yours, and it's not a huge deal.  I trust you to do what makes sense in the situation.  If you send them to me, then we can explore a whole world of possibilities together.  That's worth a lot more than this first file - you'll see.
</p>

<p>
  The iseries consists of 5 meditations.
</p>
  
<p>
  <i>
    ireceive -- iaccept -- idream -- idesire -- icommit
  </i>
</p>
  
<p>
  You have the first one.  For the other four I ask a few dollars.  There are some other exciting projects I'd love to share with you as well.
</p>

<p>
  I convene a monthly group for women (and other people) to explore and expand their feminine energy.  To join the Receptivity Goddess Group, <%= link_to 'fill out the application on this page.', new_goddess_url %>
</p>

<p>
  If you live in or near Brooklyn, or can travel there, you can join us in person on Monday evenings (7-9 PM on the first Monday of each month).  Alternately, you are welcome to join the online group, which meets on Thursday afternoons (1-3 PM on the first Thursday of each month).  I believe that this group is one of the best investments you can make in evolving your attitude, your skills and your life.  I highly recommend that you join the Receptivity Goddess Group!
</p>

<p>
  Thank you so very much!
</p>

<p>
  Sincerely,
</p>

<p>
  -Emily
</p>

app/views/gift/initiate.text.erb
Hello!

We are learning about receiving gifts.  Here is one I have for you.  It is a meditation, an audio file, and I would like for you to listen to it!

You should be able to open this file on any computer and load it onto any phone, device or player.  If you would like to share it with someone else, you can, but I ask that instead of sending them your file, please direct them to <%= root_url %> and tell them that they can get the meditation, and more, by just providing their email address (or signing up via Facebook).  Thank you!!  The choice is yours, and it's not a huge deal.  I trust you to do what makes sense in the situation.  If you send them to me, then we can explore a whole world of possibilities together.  That's worth a lot more than this first file - you'll see.

The iseries consists of 5 meditations.

ireceive -- iaccept -- idream -- idesire -- icommit

You have the first one.  For the other four I ask a few dollars.  There are some other exciting projects I'd love to share with you as well.

I convene a monthly group for women (and other people) to explore and expand their feminine energy.  To join the Receptivity Goddess Group, fill out the application on this page. <%= new_goddess_url %>

If you live in or near Brooklyn, or can travel there, you can join us in person on Monday evenings (7-9 PM on the first Monday of each month).  Alternately, you are welcome to join the online group, which meets on Thursday afternoons (1-3 PM on the first Thursday of each month).  I believe that this group is one of the best investments you can make in evolving your attitude, your skills and your life.  I highly recommend that you join the Receptivity Goddess Group!

Thank you so very much!

Sincerely,

-Emily

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReceiveEverything</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= fb_connect_async_js %>
    <%= csrf_meta_tags %>
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,200,700' rel='stylesheet' type='text/css'>
  </head>
  <body background-color="transparent">
    <p id="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <% unless current_mystic %>
      <%= link_to 'Create an account / Sign in', '#registration_pane', :class => 'fancybox', :id => 'login_signup_form_link' %> or
      <%= fb_login_and_redirect(new_session_facebook_path, :scope => 'email') %>
    <% end %>

    <%= yield %>

  <nav id="footer">
    <% if current_creatrix %>
      <%= link_to 'share links', share_links_path %>
      <%= link_to 'meditations', meditations_path %>
      <%= link_to 'products', products_path %>
      <%= link_to 'inclusions', inclusions_path %>
      <%= link_to 'prices', prices_path %>
      <%= link_to 'mystics', mystics_path %>
      <%= link_to 'accesses', accesses_path %>
      <%= link_to 'sign out', destroy_creatrix_session_path, :method => :delete %>
    <% end %>
    <%= link_to 'log out', destroy_mystic_session_path, :method => :delete if current_mystic %>
  </nav>
  
  <div id="registration_pane">
    <%= fb_login_and_redirect(new_session_facebook_path, :scope => 'email') %>
    <div id="sign_up">
      <h2>Sign up</h2>

      <%= form_for(Mystic.new, :as => 'mystic', :url => registration_path(:mystic)) do |f| %>

        <div><%= f.label :email %><br />
        <%= f.email_field :email, :autofocus => true %></div>

        <div><%= f.label :password %><br />
        <%= f.password_field :password %></div>

        <div><%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation %></div>

        <div><%= f.submit "Sign up", :id => 'sign_up_button' %></div>
      <% end %>
    </div>
    
    <div id="sign_in">
      <h2>Sign in</h2>

      <%= form_for(Mystic.new, :as => 'mystic', :url => session_path(:mystic)) do |f| %>
        <div><%= f.label :email %><br />
        <%= f.email_field :email, :autofocus => true %></div>

        <div><%= f.label :password %><br />
        <%= f.password_field :password %></div>

        <% if Devise.mappings[:mystic].rememberable? -%>
          <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
        <% end -%>

        <div><%= f.submit "Sign in" %></div>
      <% end %>
    </div>

    <%#= render "devise/shared/links" %>
  </div>
  
  </body>
</html>