config/routes.rb
ReceiveEverything::Application.routes.draw do
  resources :comments do
    member do
      get :reply
    end
  end

  resources :share_links do
    member do
      get :sharer
      put :shared
    end
  end

  resources :goddesses
  resources :purchases do
    collection do
      get :mine
    end
  end

  devise_for :creatrixes
  resources :prices

  resources :inclusions do
    member do
      put :move_higher
      put :move_lower
    end
  end
  
  resources :accesses

  resources :products do
    resources :inclusions
    member do
      get :display
      put :move_higher
      put :move_lower
    end
    collection do
      get :browse
    end
  end

  resources :meditations do
    collection do
      get :browse
    end
    member do
      get :display
    end
  end

  devise_for :mystics
  resources :mystics do
    collection do
      get :logged_in
      post :grant
    end
  end
  get 'facebook_new_session' => 'facebook#new_session', :as => 'new_session_facebook'
  
  root :to => 'products#browse'

end

app/models/meditation.rb
class Meditation < ActiveRecord::Base
  has_many :inclusions
  has_many :products, :through => :inclusions
  
  has_many :accesses
  has_many :mystics, :through => :accesses
  
  has_many :comments, :as => :subject
  
  scope :not_in_product, lambda { |product| product.inclusions.any? ? where('id not in (?)', product.inclusions.map(&:meditation_id)) : nil }
  scope :free, lambda { where :free => true }
  scope :active, lambda { where :active => true }
  
  def current_price_in_cents
    products.first.andand.current_price_in_cents
  end
  
  def current_price_in_dollars
    current_price_in_cents.andand./ 100.0
  end
end

app/controllers/meditations_controller.rb
class MeditationsController < ApplicationController
  before_action :set_meditation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_creatrix!, except: [:browse, :display]
  before_action :authenticate_mystic!, only: [:browse, :display]
  
  def browse
    @meditations = Meditation.active
  end
  
  def display
    @meditation = Meditation.find params[:id]
  end

  # GET /meditations
  # GET /meditations.json
  def index
    @meditations = Meditation.all
  end

  # GET /meditations/1
  # GET /meditations/1.json
  def show
  end

  # GET /meditations/new
  def new
    @meditation = Meditation.new
  end

  # GET /meditations/1/edit
  def edit
  end

  # POST /meditations
  # POST /meditations.json
  def create
    @meditation = Meditation.new(meditation_params)

    respond_to do |format|
      if @meditation.save
        format.html { redirect_to @meditation, notice: 'Meditation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @meditation }
      else
        format.html { render action: 'new' }
        format.json { render json: @meditation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meditations/1
  # PATCH/PUT /meditations/1.json
  def update
    respond_to do |format|
      if @meditation.update(meditation_params)
        format.html { redirect_to @meditation, notice: 'Meditation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @meditation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meditations/1
  # DELETE /meditations/1.json
  def destroy
    @meditation.destroy
    respond_to do |format|
      format.html { redirect_to meditations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meditation
      @meditation = Meditation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meditation_params
      params.require(:meditation).permit(:name, :soundcloud_url, :free, :active, :embed)
    end
end

app/helpers/meditations_helper.rb
module MeditationsHelper
  def soundcloud_embed_for_meditation meditation
    %Q!<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=#{meditation.soundcloud_url}&amp;color=ff6600&amp;auto_play=false&amp;show_artwork=true"></iframe>!.html_safe
  end
end

app/views/meditations/_form.html.erb
<%= form_for(@meditation) do |f| %>
  <% if @meditation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meditation.errors.count, "error") %> prohibited this meditation from being saved:</h2>

      <ul>
      <% @meditation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :soundcloud_url %><br>
    <%= f.text_field :soundcloud_url %>
  </div>
  <div class="field">
    <%= f.label :free %><br>
    <%= f.check_box :free %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :embed %><br>
    <%= f.text_field :embed %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meditations/browse.html.erb
<div id="meditations">
  <% @meditations.each do |meditation| %>
    <%= div_for meditation do %>
      <% if current_mystic.has_access_to? meditation %>
        <%= link_to meditation.name, display_meditation_path(meditation) %>
      <% else %>
        <header class="meditation_name">
          <%= meditation.name %>
        </header>
        <%= form_tag purchases_path do %>
          <%= hidden_field_tag :product_id, meditation.products.first.andand.id %>
          <article>
            <label class="amount">
              <span>Price: <%= number_to_currency meditation.current_price_in_dollars %></span>
            </label>
          </article>

          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-description="<%= meditation.name %>"
                  data-amount="<%= meditation.current_price_in_cents %>"></script>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/meditations/display.html.erb
<%= div_for @meditation do %>
  <header>
    <%= @meditation.name %>
  </header>
  <section>
    <%= @meditation.embed.html_safe %>
  </section>
<% end %>

app/views/meditations/edit.html.erb
<h1>Editing meditation</h1>

<%= render 'form' %>

<%= link_to 'Show', @meditation %> |
<%= link_to 'Back', meditations_path %>

app/views/meditations/index.html.erb
<h1>Listing meditations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Soundcloud url</th>
      <th>Creator</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @meditations.each do |meditation| %>
      <tr>
        <td><%= meditation.name %></td>
        <td><%= meditation.soundcloud_url %></td>
        <td><%= meditation.creator_id %></td>
        <td><%= link_to 'Show', meditation %></td>
        <td><%= link_to 'Edit', edit_meditation_path(meditation) %></td>
        <td><%= link_to 'Destroy', meditation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meditation', new_meditation_path %>

app/views/meditations/new.html.erb
<h1>New meditation</h1>

<%= render 'form' %>

<%= link_to 'Back', meditations_path %>

app/views/meditations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meditation.name %>
</p>

<p>
  <strong>Soundcloud url:</strong>
  <%= @meditation.soundcloud_url %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @meditation.creator_id %>
</p>

<p>
  <%= @meditation.embed.andand.html_safe %>
</p>

<%= link_to 'Edit', edit_meditation_path(@meditation) %> |
<%= link_to 'Back', meditations_path %>