config/routes.rb
ReceiveEverything::Application.routes.draw do
  resources :comments do
    member do
      get :reply
    end
  end

  resources :share_links do
    member do
      get :sharer
      put :shared
    end
  end

  resources :goddesses
  resources :purchases do
    collection do
      get :mine
    end
  end

  devise_for :creatrixes
  resources :prices

  resources :inclusions do
    member do
      put :move_higher
      put :move_lower
    end
  end
  
  resources :accesses

  resources :products do
    resources :inclusions
    member do
      get :display
      put :move_higher
      put :move_lower
    end
    collection do
      get :browse
    end
  end

  resources :meditations do
    collection do
      get :browse
    end
    member do
      get :display
    end
  end

  devise_for :mystics
  resources :mystics do
    collection do
      get :logged_in
      post :grant
    end
  end
  get 'facebook_new_session' => 'facebook#new_session', :as => 'new_session_facebook'
  
  root :to => 'products#browse'

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :inclusions, :order => :position
  has_many :meditations, :through => :inclusions
  has_many :prices
  
  scope :ordered, lambda { order(:position) }
  scope :active, lambda { where(:active => true) }
  acts_as_list
  
  def current_price
    prices.current.active.lowest.first
  end
  
  def current_price_in_cents
    current_price.andand.cents.to_i
  end
  
  def current_price_in_dollars
    current_price_in_cents / 100.0
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:display, :show, :edit, :update, :move_higher, :move_lower, :destroy]
  before_action :authenticate_creatrix!, :except => [:browse, :display]
  before_action :authenticate_mystic!, :only => :display

  def browse
    @products = Product.ordered.active
  end
  
  def display
    (redirect_to(root_url) && return) unless current_mystic.has_access_to_product? @product
  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.ordered
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def move_higher
    @product.move_higher
    redirect_to products_path
  end
  
  def move_lower
    @product.move_lower
    redirect_to products_path
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :active)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/browse.html.erb
<script>
  check_mystic_login();
  check_mystic_purchases();
</script>
<div id="products">
  <% @products.each do |product| %>
    <%= div_for product do %>
      <%= product.name %>
      <article>
        <% unless current_mystic.andand.has_access_to_product?(product) %>
          <label class="amount">
            <span class="price"><%= number_to_currency product.current_price_in_dollars %></span>
          </label>
        <% end %>
      </article>
      <script src="https://checkout.stripe.com/checkout.js"></script>
      <script>      
        var <%= "purchasing_#{product.id}" %> = StripeCheckout.configure({
          key: '<%= Rails.configuration.stripe[:publishable_key] %>',
          image: '<%= asset_path 'Emily_Tepper_watermark.png' %>',
          token: function(token, args) {
            $.ajax({url: '/purchases', type: 'POST', data: {product_id: <%= product.id %>, stripeToken: token.id}});
          },
          closed: function() {
            window.location = '/products/<%= product.id %>/display';
          }
        });

        <% if product.current_price_in_cents > 0 %>

          $('#<%= dom_id product %>').click(function(e) {
            if (mystic_logged_in) {
              if ($.inArray(<%= product.id %>, mystic_purchases) != -1) {
                window.location = '/products/<%= product.id %>/display'; 
              } else {
                <%= "purchasing_#{product.id}" %>.open({
                  name: '<%= product.name %>',
                  amount: <%= product.current_price_in_cents %>
                });
              }
            } else {
              $('#login_signup_form_link').click();
            }
            e.preventDefault();
          });
          
        <% else %>
        
          $('#<%= dom_id product %>').click(function(e) {
            if (mystic_logged_in) {
              window.location = '/products/<%= product.id %>/display';
            } else {
              $('#login_signup_form_link').click();
            }
          });
          
        <% end %>
      </script>
    <% end %>
  <% end %>
</div>
<div id="goddess_group_opportunity">
  <%= link_to 'Want more?', new_goddess_path, :id => 'goddess_wants_more' %>
</div>

app/views/products/display.html.erb
<%= link_to 'Review all our products', browse_products_path %>
<%= link_to_function 'Learn about the Receptivity Goddess Group', "window.location = '/goddesses/new'" %>

<% @product.meditations.each do |meditation| %>
  <%= div_for meditation do %>
    <header>
      <%= meditation.name %>
    </header>
    <section>
      <%= meditation.embed.andand.html_safe %>
    </section>
    <section>
      <%= comment_form_for meditation %>
      <%= display_comments_on meditation %>
    </section>
  <% end %>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Add a meditation to this product', new_product_inclusion_path(@product), :remote => true %>

<div id="new_inclusion_holder">
  
</div>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Current Price</th>
      <th>Active</th>
      <th>Creator</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.current_price_in_cents %></td>
        <td><%= product.active %></td>
        <td><%= product.creator_id %></td>
        <td><%= link_to 'move higher', move_higher_product_path(product), :method => :put %></td>
        <td><%= link_to 'move lower', move_lower_product_path(product), :method => :put %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<div id="meditations_included_in_product">
  <% @product.meditations.each do |meditation| %>
    <%= div_for meditation do %>
      <%= link_to_name meditation %>
    <% end %>
  <% end %>
</div>

<p>
  <strong>Active:</strong>
  <%= @product.active %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @product.creator_id %>
</p>

<div>
  <% @product.meditations.each do |meditation| %>
    <div>
      <%= link_to_name meditation %>
    </div>
  <% end %>
</div>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>