config/routes.rb
ReceiveEverything::Application.routes.draw do
  resources :comments do
    member do
      get :reply
    end
  end

  resources :share_links do
    member do
      get :sharer
      put :shared
    end
  end

  resources :goddesses
  resources :purchases do
    collection do
      get :mine
    end
  end

  devise_for :creatrixes
  resources :prices

  resources :inclusions do
    member do
      put :move_higher
      put :move_lower
    end
  end
  
  resources :accesses

  resources :products do
    resources :inclusions
    member do
      get :display
      put :move_higher
      put :move_lower
    end
    collection do
      get :browse
    end
  end

  resources :meditations do
    collection do
      get :browse
    end
    member do
      get :display
    end
  end

  devise_for :mystics
  resources :mystics do
    collection do
      get :logged_in
      post :grant
    end
  end
  get 'facebook_new_session' => 'facebook#new_session', :as => 'new_session_facebook'
  
  root :to => 'products#browse'

end

app/models/share_link.rb
class ShareLink < ActiveRecord::Base
  belongs_to :creatrix
end

app/controllers/share_links_controller.rb
class ShareLinksController < ApplicationController
  before_action :set_share_link, only: [:sharer, :shared, :show, :edit, :update, :destroy]
  before_action :authenticate_creatrix!, except: [:sharer, :shared]

  def sharer
    @share_link.clicks = @share_link.clicks.to_i + 1
    @share_link.save
  end
  
  def shared
    @share_link.shares = @share_link.shares.to_i + 1
    @share_link.save
    render :nothing => true
  end

  # GET /share_links
  # GET /share_links.json
  def index
    @share_links = ShareLink.all
  end

  # GET /share_links/1
  # GET /share_links/1.json
  def show
  end

  # GET /share_links/new
  def new
    @share_link = ShareLink.new
  end

  # GET /share_links/1/edit
  def edit
  end

  # POST /share_links
  # POST /share_links.json
  def create
    @share_link = ShareLink.new(share_link_params)

    respond_to do |format|
      if @share_link.save
        format.html { redirect_to @share_link, notice: 'Share link was successfully created.' }
        format.json { render action: 'show', status: :created, location: @share_link }
      else
        format.html { render action: 'new' }
        format.json { render json: @share_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /share_links/1
  # PATCH/PUT /share_links/1.json
  def update
    respond_to do |format|
      if @share_link.update(share_link_params)
        format.html { redirect_to @share_link, notice: 'Share link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @share_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /share_links/1
  # DELETE /share_links/1.json
  def destroy
    @share_link.destroy
    respond_to do |format|
      format.html { redirect_to share_links_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_share_link
      @share_link = ShareLink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def share_link_params
      params.require(:share_link).permit(:url, :clicks, :shares, :creatrix_id, :description, :image)
    end
end

app/helpers/share_links_helper.rb
module ShareLinksHelper
end

app/views/share_links/_form.html.erb
<%= form_for(@share_link) do |f| %>
  <% if @share_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@share_link.errors.count, "error") %> prohibited this share_link from being saved:</h2>

      <ul>
      <% @share_link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <%= f.hidden_field :creatrix_id, :value => current_creatrix.id %>
<% end %>

app/views/share_links/edit.html.erb
<h1>Editing share_link</h1>

<%= render 'form' %>

<%= link_to 'Show', @share_link %> |
<%= link_to 'Back', share_links_path %>

app/views/share_links/index.html.erb
<h1>Listing share_links</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Sharable Link</th>
      <th>Clicks</th>
      <th>Shares</th>
      <th>Description</th>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @share_links.each do |share_link| %>
      <tr>
        <td><%= share_link.url %></td>
        <td><%= sharer_share_link_url share_link %></td>
        <td><%= share_link.clicks %></td>
        <td><%= share_link.shares %></td>
        <td><%= share_link.description %></td>
        <td><%= share_link.image %></td>
        <td><%= link_to 'Show', share_link %></td>
        <td><%= link_to 'Edit', edit_share_link_path(share_link) %></td>
        <td><%= link_to 'Destroy', share_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Share link', new_share_link_path %>

app/views/share_links/new.html.erb
<h1>New share_link</h1>

<%= render 'form' %>

<%= link_to 'Back', share_links_path %>

app/views/share_links/sharer.html.erb
<script type='text/javascript'>
  share_it = function() {
    FB.login(function(response) {
      if(response.authResponse) {
        FB.api('/me/feed', 'post', { message: '<%= @share_link.description %>', link: '<%= @share_link.url %>' }, function(response) {
          if (!response || response.error) {
        
          } else {
            alert('Thank you ever so much.  I am very excited to see what your Facebook friends bring to my community.  You can tell them I said so!');
            $.ajax({'url': '<%= shared_share_link_path @share_link %>', 'type': 'PUT'});
            window.location = '<%= new_session_facebook_path %>';
          }
        });
      } else {
        $('#non_authorized_sharer_link').click()
      }
    }, {'scope': ['publish_actions', 'email']});
  }
</script>

<script type="text/javascript">
  $(function() {
    $('#non_authorized_sharer_link').fancybox();
  });
</script>
<div id="share_link_description">
  <%= @share_link.description %>
</div>

<div id="sharable_link">
  The URL you are asked to share: 
  <%= link_to @share_link.url, @share_link.url, :target => '_blank' %>
</div>

<div id="sharer_hider">
  <div id="sharer_prompter">
    Ready to share this message and URL?
    <%= link_to 'Yes.', '#', :onclick => 'share_it();' %>
  </div>
</div>

<div id="non_authorized_option">
  <%= link_to 'Share without authorizing our Facebook app', '#non_authorized_sharer', :id => 'non_authorized_sharer_link' %>
</div>

<div id="non_authorized_sharer_hider">
  <div id="non_authorized_sharer">
    <%= link_to 'Share the link without using that Facebook app', "https://www.facebook.com/sharer/sharer.php?u=#{@share_link.url}", :target => '_blank' %>
  </div>
</div>

app/views/share_links/show.html.erb
<p id="notice"><%= notice %></p>

<p id="sharable_link">
  Here is the link you should share.
  <%= sharer_share_link_url @share_link %>
</p>

<p>
  <strong>Url:</strong>
  <%= @share_link.url %>
</p>

<p>
  <strong>Clicks:</strong>
  <%= @share_link.clicks %>
</p>

<p>
  <strong>Shares:</strong>
  <%= @share_link.shares %>
</p>

<p>
  <strong>Description:</strong>
  <%= @share_link.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @share_link.image %>
</p>

<%= link_to 'Edit', edit_share_link_path(@share_link) %> |
<%= link_to 'Back', share_links_path %>